// -----------------------------------------------------------------------------
// ValueSet
// -----------------------------------------------------------------------------
ValueSet: DHDDiagnoseThesaurusHHT
Id: dhd-dx-thesaurus-hnc
Title: "DHD DiagnoseThesaurus: codes voor HHT"
Description: "HHT Diagnoses, zoals gecodeerd/gebruikt binnen de DHD DiagnoseThesaurus."
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000880  "maligne neoplasma van uitwendige bovenlip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000883  "maligne neoplasma van uitwendige onderlip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000886  "maligne neoplasma van uitwendige lip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000887  "maligne neoplasma van binnenzijde van bovenlip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000890  "maligne neoplasma van binnenzijde van onderlip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000893  "maligne neoplasma van binnenzijde van lip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000896  "maligne neoplasma van commissuur van lip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000899  "maligne neoplasma met overlappende lokalisatie van lip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000902  "maligne neoplasma van lip"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000903  "maligne neoplasma van tongbasis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000906  "maligne neoplasma van dorsaal oppervlak van tong"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000909  "maligne neoplasma van tongrand"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000912  "maligne neoplasma van ventraal oppervlak van tong"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000915  "maligne neoplasma van voorste tweederde deel van tong"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000916  "maligne neoplasma van tonsilla lingualis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000919  "maligne neoplasma met overlappende lokalisatie van tong"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000922  "maligne neoplasma van tong"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000923  "maligne neoplasma van tandvlees van bovenkaak"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000926  "maligne neoplasma van tandvlees van onderkaak"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000929  "maligne neoplasma van tandvlees"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000930  "maligne neoplasma van voorste deel van mondbodem"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000933  "maligne neoplasma van laterale deel van mondbodem"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000936  "maligne neoplasma met overlappende lokalisatie van mondbodem"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000939  "maligne neoplasma van mondbodem"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000940  "maligne neoplasma van hard gehemelte"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000943  "maligne neoplasma van zacht gehemelte"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000946  "maligne neoplasma van uvula"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000949  "maligne neoplasma met overlappende lokalisatie van gehemelte"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000952  "maligne neoplasma van gehemelte"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000953  "maligne neoplasma van wangslijmvlies"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000956  "maligne neoplasma van vestibulum oris"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000959  "maligne neoplasma van retromolaire gebied"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000962  "maligne neoplasma met overlappende lokalisatie van mond"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000965  "maligne neoplasma van mond"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000966  "maligne neoplasma van kleine speekselklier"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000967  "maligne neoplasma van glandula parotidea"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000968  "maligne neoplasma van glandula submandibularis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000969  "maligne neoplasma van glandula sublingualis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000970  "maligne neoplasma met overlappende lokalisatie van grote speekselklieren"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000971  "maligne neoplasma van grote speekselklier"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000972  "maligne neoplasma van tonsilnis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000975  "maligne neoplasma van gehemelteboog"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000978  "maligne neoplasma met overlappende lokalisatie van tonsil"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000981  "maligne neoplasma van tonsil"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000982  "maligne neoplasma van vallecula epiglottica"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000985  "maligne neoplasma van voorste oppervlak van epiglottis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000988  "maligne neoplasma van laterale wand van orofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000991  "maligne neoplasma van achterwand van orofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000994  "maligne neoplasma van kieuwspleet"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000000997  "maligne neoplasma met overlappende lokalisatie van orofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001000  "maligne neoplasma van orofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001001  "maligne neoplasma van bovenwand van nasofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001004  "maligne neoplasma van achterwand van nasofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001007  "maligne neoplasma van laterale wand van nasofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001010  "maligne neoplasma van voorwand van nasofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001013  "maligne neoplasma met overlappende lokalisatie van nasofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001016  "maligne neoplasma van nasofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001018  "maligne neoplasma van sinus piriformis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001021  "maligne neoplasma van postcricoïde regio"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001024  "maligne neoplasma van plica aryepiglottica aan hypofaryngeale zijde"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001027  "maligne neoplasma van achterwand van hypofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001030  "maligne neoplasma met overlappende lokalisatie van hypofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001033  "maligne neoplasma van hypofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001034  "maligne neoplasma van farynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001035  "maligne neoplasma van ring van Waldeyer"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001036  "maligne neoplasma met overlappende lokalisatie van lip, mond- en keelholte"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001125  "maligne neoplasma van neusholte"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001126  "maligne neoplasma van middenoor"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001127  "maligne neoplasma van sinus maxillaris"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001128  "maligne neoplasma van sinus ethmoidalis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001129  "maligne neoplasma van sinus frontalis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001130  "maligne neoplasma van sinus sphenoidalis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001131  "maligne neoplasma met overlappende lokalisatie van neusbijholten"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001132  "maligne neoplasma van neusbijholte"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001133  "maligne neoplasma van glottis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001136  "maligne neoplasma van supraglottis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001139  "maligne neoplasma van subglottis"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001142  "maligne neoplasma van laryngeaal kraakbeen"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001145  "maligne neoplasma met overlappende lokalisatie van larynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001148  "maligne neoplasma van larynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000001488  "metastase in lymfeklier van hals"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000037100  "primair maligne neoplasma van alveolaire mucosa"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000052938  "nasofarynxcarcinoom"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000052939  "recidief nasofarynxcarcinoom"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000053218  "metastase in lymfeklieren van hoofd en hals"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000061955  "maligne neoplasma van mondholte"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062466  "polymorf laaggradig adenocarcinoom van speekselklieren"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062467  "adenocarcinoom van speekselklieren"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062469  "sinonasaal ongedifferentieerd carcinoom"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062471  "plaveiselcelcarcinoom van tonsil"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062472  "plaveiselcelcarcinoom van speekselklieren"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062473  "plaveiselcelcarcinoom van larynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062474  "plaveiselcelcarcinoom van hypofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062475  "plaveiselcelcarcinoom in orofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062476  "plaveiselcelcarcinoom in nasofarynx"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062482  "muco-epidermoïd carcinoom van speekselklieren"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062501  "ethmoïdcarcinoom"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062512  "carcinoom van mondbodem"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062587  "adenoïd cysteus carcinoom van speekselklieren"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062631  "acinic cell carcinoom van speekselklieren"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000062690  "carcinoom-ex-pleiomorf adenoom van speekselklieren"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000095986  "esthesioneuroblastoom"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000098042  "maligne epitheliaal neoplasma van systema salivaria"
* https://plugin.healthcare/fhir/CodeSystem/dhd-dx-thesaurus#0000099959  "maligne neoplasma van inwendige gehoorgang"
